version: 2.0

references:
  workspace: &workspace
    ~/shapeofview

  config_android: &config_android
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

  config_gcloud: &config_gcloud
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
      TERM: dumb

  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - ftl-tests
        - build
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

jobs:
  build:
    <<: *config_android

    steps:
      - checkout
      - *restore_cache

      - run:
          name: Compile
          command: ./gradlew assemble assembleAndroidTest --no-daemon
      - store_artifacts:
          path: build/outputs/aar
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/distributions/

      - run:
          name: JVM Tests & Lint
          command: ./gradlew check --no-daemon
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results
      - store_artifacts:
          path: build/reports/lint-results.html
      - store_test_results:
          path: build/reports

      - *save_cache
      - *persist_to_workspace

workflows:
  version: 2
  build_and_test:
    jobs:
      - build